version: "3.8"
services:
  mpp-song-api:
    container_name: mpp-song-server
    volumes:
      - ./server:/server
      - /server/node_modules
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    ports:
      - "8181:8181"
